### ISSUE TITLE
Case Study 4

### ISSUE THREAD

**Issue by ferrin8** [BYUI335/M335_SP20_Pohlsander_Conn#2]
I loved your last few graphs! It really showed which age groups were most at risk. The first graph could probably be reworked since color/hue isn't the most ideal way to encode a continuous variable, but I really liked all the others!

**Comment by Cannonmb** [comment]
Add a title to the cool geom_levels plot. Also see if you're able to change the label of the legend. the user won't know what "n" means. You can change this in the labs() function. labs(fill/color = "legend title")

**Comment by conjonpo** [comment]
Done.
