### ISSUE TITLE
Case Study 5

### ISSUE THREAD

**Issue by eliseps** [BYUI335/M335_SP20_Pohlsander_Conn#5]
I think your graphs look great for the most part. A couple of things I did notice is that you could go through and change your axis labels (height.cm would look better as "Height (in cm)" and b19, g19, etc should be changed. I'm not sure what those really represent) Also, your second graph should be adjusted so that the space between each individual graph provides the x-axis to be viewed more clearly.

**Comment by conjonpo** [comment]
Done.
